language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pipenv install mypy

script:
  - mypy --strict-optional magazin
  - pytest

after_success:
  - pip install coveralls
  - coveralls
