language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install mypy

script:
  - mypy --strict-optional .
  - pytest

after_success:
  - pip install coveralls
  - coveralls
